chef/chef_dictionary

- chef.txt
Added tech words to chef org dictionary
`Dobi`, `direnv` and `envrc` are going to be more widely used within the chef org so we may as well add these here to avoid confusion and errors
Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>
- [x ] New feature (non-breaking change which adds functionality)
> Add words that will be used more commonly in chef org

- chef.txt
Signed-off-by: kagarmoe <kgarmoe@chef.io>
> add macinbox

- docs.txt
Signed-off-by: Kimberly Garmoe <kgarmoe@chef.io>
Terms from the Postgresql 13 upgrade
> add reindex, reindexdb, vacuumdb

- docs.txt
Signed-off-by: Tim Smith <tsmith@chef.io>
> Add MTLS to the dictionary

- docs.txt
Signed-off-by: kagarmoe <kgarmoe@chef.io>
Add a few words that failed in Supermarket
> Add Supermarket words

- docs.txt
Signed-off-by: kagarmoe <kgarmoe@chef.io>
<
> Words from Chef Manage release notes

- docs.txt
Signed-off-by: kagarmoe <kgarmoe@chef.io>
Removes the blank line at the start of the file that I added in my last PR.
> Remove blankline at beginning of file

- docs.txt
Signed-off-by: kagarmoe <kimberly.garmoe@progress.com>
> Workstation vocab

- docs.txt
Add a couple more words to the docs dictionary
> Add words to docs dictionary

- docs.txt
A few more words for the docs dictionary.
> Add more words to docs dictionary

- chef.txt
Add fcontext to chef dictionary.
> Add fcontext to chef dictionary

- README.md
- docs.txt
Add a couple forbidden words to the dictionary and a bit more information to the readme.
> Add words and a bit more context in readme

- chef.txt
- docs.txt
> Add a couple words to dict

- chef.txt
- docs.txt
Add a few more words to the dictionary.
> More words

- docs.txt
Adding words related to Server and Workstation docs.
> Add more words to dictionary

- docs.txt
More words for Workstation and Server docs.
#24 
chef/chef-web-docs#4152
> Add more words

- docs.txt
> Add subkey subkeys

- docs.txt
> Add STARTTLS to docs dictionary

- docs.txt
> Add SaaS to dictionary

- docs.txt
> add Grammarly

- docs.txt
> Add one more

- docs.txt
> Add quickstart

- docs.txt
> Add new word

- chef.txt
fixing a build error on: https://github.com/chef/chef/pull/14822 
```
Warning: Unknown word (hawkey)
lib/chef/provider/package/dnf/dnf_helper.py:6:8 Unknown word (hawkey)
lib/chef/provider/package/dnf/dnf_helper.py:10:29 Unknown word (ujson)
lib/chef/provider/package/dnf/dnf_helper.py:13:[12](https://github.com/chef/chef/actions/runs/12957005787/job/36317267550?pr=14822#step:4:13) Unknown word (ujson)
lib/chef/provider/package/dnf/dnf_helper.py:25:14 Unknown word (installroot)
lib/chef/provider/package/dnf/dnf_helper.py:26:14 Unknown word (assumeyes)
lib/chef/provider/package/dnf/dnf_helper.py:28:36 Unknown word (installroot)
lib/chef/provider/package/dnf/dnf_helper.py:61:19 Unknown word (versionstr)
lib/chef/provider/package/dnf/dnf_helper.py:65:19 Unknown word (versionstr) …
```
> adding new words based off of https://github.com/chef/chef/pull/14822

- 360-docs.txt
> Add cafile to 360 docs
